import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex items-center justify-center h-20 w-full bg-blue-900 ">Header</div>
        {children}
        <div className=" flex items-center justify-center h-20 w-full bg-blue-400 ">Footer</div>
      </body>
    </html>
  );
}
